# 全局检测模式配置: keyword, regex, mixed
detection_mode: mixed

log_paths:
  - "/var/log"
  - "./test.log"

detectors:
  oom:
    enabled: true
    detection_mode: mixed  # 可单独覆盖全局模式
    keywords:
      - "Out of memory"
      - "oom-killer"
      - "Killed process"
      - "Memory cgroup out of memory"
    regex_patterns:
      - "Out\\s+of\\s+memory"
      - "oom[\\-\\s]*killer"
      - "Killed\\s+process\\s+\\d+"
      - "Memory\\s+cgroup\\s+out\\s+of\\s+memory"
    
  panic:
    enabled: true
    detection_mode: mixed
    keywords:
      - "Kernel panic"
      - "kernel panic"
      - "not syncing"
      - "System halted"
      - "sysrq triggered crash"
      - "Unable to mount root"
    regex_patterns:
      - "Kernel\\s+panic"
      - "not\\s+syncing"
      - "System\\s+halted"
      - "sysrq\\s+triggered\\s+crash"
      - "Unable\\s+to\\s+mount\\s+root"
      
  reboot:
    enabled: true
    detection_mode: mixed
    keywords:
      - "unexpectedly shut down"
      - "unexpected restart"
      - "system reboot"
      - "restart triggered by hardware"
    regex_patterns:
      - "unexpectedly\\s+shut\\s+down"
      - "unexpected\\s+restart"
      - "system\\s+reboot"
      - "restart\\s+triggered\\s+by\\s+hardware"
  
  oops:
    enabled: true
    detection_mode: mixed
    keywords:
      - "Oops:"
      - "general protection fault"
      - "kernel BUG at"
      - "Unable to handle kernel"
      - "WARNING: CPU:"
      - "BUG: unable to handle kernel"
      - "invalid opcode:"
      - "stack segment:"
    regex_patterns:
      - "Oops:"
      - "general\\s+protection\\s+fault"
      - "kernel\\s+BUG\\s+at"
      - "Unable\\s+to\\s+handle\\s+kernel"
      - "WARNING:\\s+CPU:"
      - "BUG:\\s+unable\\s+to\\s+handle\\s+kernel"
      - "invalid\\s+opcode:"
      - "stack\\s+segment:"
      
  deadlock:
    enabled: true
    detection_mode: mixed
    keywords:
      - "possible deadlock"
      - "lock held"
      - "blocked for"
      - "stalled for"
      - "hung task"
      - "task blocked"
      - "soft lockup"
      - "hard lockup"
      - "blocked for more than 120 seconds"
      - "task hung"
      - "Show Blocked State"
      - "Call Trace for"
    regex_patterns:
      - "possible\\s+deadlock"
      - "lock\\s+held"
      - "blocked\\s+for"
      - "stalled\\s+for"
      - "hung\\s+task"
      - "task\\s+blocked"
      - "soft\\s+lockup"
      - "hard\\s+lockup"
      - "blocked\\s+for\\s+more\\s+than\\s+\\d+\\s+seconds"
      - "task\\s+hung"
      - "Show\\s+Blocked\\s+State"
      - "Call\\s+Trace\\s+for"

  fs_exception:
    enabled: true
    detection_mode: mixed
    keywords:
      - "filesystem error"
      - "EXT4-fs error"
      - "XFS error"
      - "I/O error"
      - "file system corruption"
      - "superblock corrupt"
      - "metadata corruption"
      - "fsck needed"
      - "Buffer I/O error"
    regex_patterns:
      - "filesystem\\s+error"
      - "EXT4-fs\\s+error"
      - "XFS\\s+error"
      - "I/O\\s+error"
      - "file\\s+system\\s+corruption"
      - "superblock\\s+corrupt"
      - "metadata\\s+corruption"
      - "fsck\\s+needed"
      - "Buffer\\s+I/O\\s+error"